variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.kittmedia.com:wordpress/deploy-script.git
    - chmod +x deploy-script/*.sh

stages:
    - staging
    - production

upload_live:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER --theme

    only:
        - tags

    variables:
        DEPLOY_PATH: /var/www/epiphyt/wp-content/plugins/german-market-helper
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION

upload_dev:
    stage: staging

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_TEST -d $DEPLOY_PATH -h $DEPLOY_SERVER --theme

    only:
        - master

    variables:
        DEPLOY_PATH: /var/www/dev/epiphyt/wp-content/plugins/german-market-helper
        DEPLOY_SERVER: hoth.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_TEST
